swagger: "2.0"
info:
  description: "API de conversão de temperatura - 1.0"
  version: "1.0.0"
  title: "Conversão de temperatura"
  contact:
    email: "fabricio@kubedev.io"
paths:
  /fahrenheit/{value}/celsius:
    get:
      description: "Converte de Fahrenheit para Celsius"
      produces:
      - "application/json"
      parameters:
      - name: "value"
        in: "path"
        description: "value que será convertido"
        required: true
        type: "number"
      responses:
        "200":
          description: "Resultado da conversão"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Temperatura"
        "400":
          description: "Bad Input Parameter"

  /celsius/{value}/fahrenheit:
    get:
      description: "Converte de Celsius para Fahrenheit"
      produces:
      - "application/json"
      parameters:
      - name: "value"
        in: "path"
        description: "value que será convertido"
        required: true
        type: "number"
      responses:
        "200":
          description: "Resultado da conversão"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Temperatura
              "
        "400":
          description: "Bad Input Parameter"

definitions:
  Temperatura:
    type: "object"
    required:
    - "value"
    properties:
      value:
        type: "number"
        example: 500.0
